# Generated By: Claude Code (claude-sonnet-4-6)
"""Shared pytest fixtures."""

import json
from pathlib import Path

import pytest

FIXTURES_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture
def sample_schedule_data():
    """Raw dict from sample_schedule.json fixture."""
    with open(FIXTURES_DIR / "sample_schedule.json") as f:
        return json.load(f)
