# Generated By: Claude Code (claude-sonnet-4-6)
"""Tests for module-level pure helper functions in d4_timer.controller."""

from d4_timer.controller import _is_game_suppressed, _next_error_backoff


class TestIsGameSuppressed:
    def test_false_when_setting_disabled(self):
        assert _is_game_suppressed(False, False) is False

    def test_false_when_game_running(self):
        assert _is_game_suppressed(True, True) is False

    def test_false_when_state_unknown(self):
        assert _is_game_suppressed(True, None) is False  # None = startup, don't suppress

    def test_true_when_enabled_and_not_running(self):
        assert _is_game_suppressed(True, False) is True


class TestNextErrorBackoff:
    def test_doubles_from_base(self):
        assert _next_error_backoff(5.0, 300.0) == 10.0

    def test_doubles_again(self):
        assert _next_error_backoff(10.0, 300.0) == 20.0

    def test_capped_at_max(self):
        assert _next_error_backoff(200.0, 300.0) == 300.0

    def test_stays_at_max(self):
        assert _next_error_backoff(300.0, 300.0) == 300.0
