# Generated By: Claude Code (claude-sonnet-4-6)
"""Tests for d4_timer.api module."""

from unittest.mock import MagicMock, patch

import pytest

from d4_timer.api import Schedule, fetch_schedule, parse_schedule
from d4_timer.config import EVENT_HELLTIDE, EVENT_LEGION, EVENT_WORLD_BOSS


class TestParseSchedule:
    def test_parses_world_boss(self, sample_schedule_data):
        schedule = parse_schedule(sample_schedule_data)
        assert len(schedule.world_boss) == 2
        ev = schedule.world_boss[0]
        assert ev.event_type == EVENT_WORLD_BOSS
        assert ev.timestamp == 1710000000
        assert ev.boss_name == "Ashava"
        assert ev.zone_name == "Scosglen"

    def test_parses_helltide(self, sample_schedule_data):
        schedule = parse_schedule(sample_schedule_data)
        assert len(schedule.helltide) == 2
        ev = schedule.helltide[0]
        assert ev.event_type == EVENT_HELLTIDE
        assert ev.timestamp == 1710001800
        assert ev.boss_name is None
        assert ev.zone_name is None

    def test_parses_legion(self, sample_schedule_data):
        schedule = parse_schedule(sample_schedule_data)
        assert len(schedule.legion) == 2
        ev = schedule.legion[0]
        assert ev.event_type == EVENT_LEGION
        assert ev.timestamp == 1710000900

    def test_empty_response(self):
        schedule = parse_schedule({})
        assert schedule.world_boss == []
        assert schedule.helltide == []
        assert schedule.legion == []

    def test_skips_entries_missing_timestamp(self):
        data = {
            "world_boss": [
                {"boss": "Ashava", "zone": [{"name": "Scosglen"}]},
                {"timestamp": 1710000000, "boss": "Wandering Death", "zone": []},
            ]
        }
        schedule = parse_schedule(data)
        assert len(schedule.world_boss) == 1
        assert schedule.world_boss[0].timestamp == 1710000000

    def test_world_boss_no_zone(self):
        data = {"world_boss": [{"timestamp": 1710000000, "boss": "Ashava", "zone": []}]}
        schedule = parse_schedule(data)
        assert schedule.world_boss[0].zone_name is None

    def test_next_event_returns_first_future(self, sample_schedule_data):
        schedule = parse_schedule(sample_schedule_data)
        # Anchor now before all fixture timestamps so both are future
        nxt = schedule.next_event(EVENT_WORLD_BOSS, now=0.0)
        assert nxt is not None
        assert nxt.timestamp == 1710000000

    def test_next_event_skips_past_events(self, sample_schedule_data):
        schedule = parse_schedule(sample_schedule_data)
        # Anchor now after the first event — should return second
        nxt = schedule.next_event(EVENT_WORLD_BOSS, now=1710000001.0)
        assert nxt is not None
        assert nxt.timestamp == 1710012600

    def test_next_event_all_past_returns_none(self, sample_schedule_data):
        schedule = parse_schedule(sample_schedule_data)
        # Anchor now after all fixture events
        nxt = schedule.next_event(EVENT_WORLD_BOSS, now=9999999999.0)
        assert nxt is None

    def test_next_event_empty_returns_none(self):
        schedule = Schedule()
        assert schedule.next_event(EVENT_WORLD_BOSS) is None

    def test_null_arrays_handled(self):
        data = {"world_boss": None, "helltide": None, "legion": None}
        schedule = parse_schedule(data)
        assert schedule.world_boss == []

    def test_timestamp_coerced_to_int(self):
        data = {"helltide": [{"timestamp": "1710001800"}]}
        schedule = parse_schedule(data)
        assert isinstance(schedule.helltide[0].timestamp, int)

    def test_skips_helltide_entries_missing_timestamp(self):
        data = {"helltide": [{}, {"timestamp": 1710001800}]}
        schedule = parse_schedule(data)
        assert len(schedule.helltide) == 1
        assert schedule.helltide[0].timestamp == 1710001800

    def test_skips_legion_entries_missing_timestamp(self):
        data = {"legion": [{}, {"timestamp": 1710000900}]}
        schedule = parse_schedule(data)
        assert len(schedule.legion) == 1
        assert schedule.legion[0].timestamp == 1710000900


class TestFetchSchedule:
    def test_returns_parsed_json(self, sample_schedule_data):
        mock_response = MagicMock()
        mock_response.json.return_value = sample_schedule_data
        mock_response.raise_for_status.return_value = None

        with patch("d4_timer.api.requests.get", return_value=mock_response) as mock_get:
            result = fetch_schedule("https://example.com/api")
            mock_get.assert_called_once_with("https://example.com/api", timeout=10)
            assert result["world_boss"][0]["boss"] == "Ashava"

    def test_raises_on_http_error(self):
        mock_response = MagicMock()
        mock_response.raise_for_status.side_effect = Exception("404 Not Found")

        with patch("d4_timer.api.requests.get", return_value=mock_response):
            with pytest.raises(Exception, match="404"):
                fetch_schedule("https://example.com/api")
