# Generated By: Claude Code (claude-sonnet-4-6)
"""
Tests derived from real helltides.com API response observed on 2026-03-08.
All tests currently pass; this file documents correct behaviour with past-timestamped events.
"""

from d4_timer.api import EventData, Schedule, parse_schedule
from d4_timer.config import EVENT_HELLTIDE, EVENT_LEGION, EVENT_WORLD_BOSS
from d4_timer.scheduler import AlertScheduler
from d4_timer.settings import Settings

# ---------------------------------------------------------------------------
# Fixture data shaped like the real API response observed on 2026-03-08.
# "now" is anchored at t=0. Negative timestamps are in the past.
# ---------------------------------------------------------------------------

NOW = 0.0

# World boss: first event is future (+92 min) — no bug here
WORLD_BOSS_EVENTS = [
    EventData(EVENT_WORLD_BOSS, timestamp=5520, boss_name="Azmodan"),  # +92 min
    EventData(EVENT_WORLD_BOSS, timestamp=11820, boss_name="Wandering Death"),
]

# Helltide: first event is 43 min in the past — bug triggers here
HELLTIDE_EVENTS = [
    EventData(EVENT_HELLTIDE, timestamp=-2580),  # -43 min (already started)
    EventData(EVENT_HELLTIDE, timestamp=1020),  # +17 min  ← correct next
    EventData(EVENT_HELLTIDE, timestamp=4620),  # +77 min
]

# Legion: first event is 3 min in the past — bug triggers here
LEGION_EVENTS = [
    EventData(EVENT_LEGION, timestamp=-180),  # -3 min (just missed)
    EventData(EVENT_LEGION, timestamp=1320),  # +22 min  ← correct next
    EventData(EVENT_LEGION, timestamp=2820),  # +47 min
]


def make_real_schedule() -> Schedule:
    s = Schedule()
    s.world_boss = list(WORLD_BOSS_EVENTS)
    s.helltide = list(HELLTIDE_EVENTS)
    s.legion = list(LEGION_EVENTS)
    return s


def make_settings() -> Settings:
    return Settings(
        alert_minutes={EVENT_WORLD_BOSS: 5, EVENT_HELLTIDE: 3, EVENT_LEGION: 2},
        enabled={EVENT_WORLD_BOSS: True, EVENT_HELLTIDE: True, EVENT_LEGION: True},
        mute_all=False,
    )


# ---------------------------------------------------------------------------
# Schedule.next_event() — should return first FUTURE event
# ---------------------------------------------------------------------------


class TestNextEventWithPastEvents:
    def test_helltide_next_event_skips_past(self):
        """next_event() must skip the -43 min past event and return +17 min."""
        s = make_real_schedule()
        nxt = s.next_event(EVENT_HELLTIDE, now=NOW)
        assert nxt is not None
        assert nxt.timestamp == 1020, (
            f"Expected +17 min event (ts=1020), got ts={nxt.timestamp} "
            f"({nxt.timestamp / 60:.1f} min from now)"
        )

    def test_legion_next_event_skips_past(self):
        """next_event() must skip the -3 min past event and return +22 min."""
        s = make_real_schedule()
        nxt = s.next_event(EVENT_LEGION, now=NOW)
        assert nxt is not None
        assert nxt.timestamp == 1320, (
            f"Expected +22 min event (ts=1320), got ts={nxt.timestamp} "
            f"({nxt.timestamp / 60:.1f} min from now)"
        )

    def test_world_boss_next_event_unaffected(self):
        """World boss first event is already future — next_event() should return it."""
        s = make_real_schedule()
        nxt = s.next_event(EVENT_WORLD_BOSS, now=NOW)
        assert nxt is not None
        assert nxt.timestamp == 5520

    def test_next_event_all_past_returns_none(self):
        """If all events are past, next_event() returns None."""
        s = Schedule()
        s.helltide = [
            EventData(EVENT_HELLTIDE, timestamp=-3600),
            EventData(EVENT_HELLTIDE, timestamp=-1800),
        ]
        nxt = s.next_event(EVENT_HELLTIDE, now=NOW)
        assert nxt is None


# ---------------------------------------------------------------------------
# Countdown display — should not show 00:00:00 when future events exist
# ---------------------------------------------------------------------------


class TestCountdownWithPastEvents:
    def test_helltide_countdown_is_not_zeroed(self):
        """Countdown for helltide must not be 00:00:00 — future event exists."""
        sched = AlertScheduler(now_fn=lambda: NOW)
        s = make_real_schedule()
        nxt = s.next_event(EVENT_HELLTIDE, now=NOW)
        result = sched.countdown_str(nxt)
        assert (
            result != "00:00:00"
        ), "Countdown shows 00:00:00 because next_event() returned a past event"
        assert result != "--:--:--"

    def test_legion_countdown_is_not_zeroed(self):
        """Countdown for legion must not be 00:00:00 — future event exists."""
        sched = AlertScheduler(now_fn=lambda: NOW)
        s = make_real_schedule()
        nxt = s.next_event(EVENT_LEGION, now=NOW)
        result = sched.countdown_str(nxt)
        assert (
            result != "00:00:00"
        ), "Countdown shows 00:00:00 because next_event() returned a past event"

    def test_helltide_countdown_shows_17_minutes(self):
        """Helltide countdown should be approximately 00:17:00."""
        sched = AlertScheduler(now_fn=lambda: NOW)
        s = make_real_schedule()
        nxt = s.next_event(EVENT_HELLTIDE, now=NOW)
        result = sched.countdown_str(nxt)
        assert result == "00:17:00", f"Got: {result}"

    def test_legion_countdown_shows_22_minutes(self):
        """Legion countdown should be approximately 00:22:00."""
        sched = AlertScheduler(now_fn=lambda: NOW)
        s = make_real_schedule()
        nxt = s.next_event(EVENT_LEGION, now=NOW)
        result = sched.countdown_str(nxt)
        assert result == "00:22:00", f"Got: {result}"


# ---------------------------------------------------------------------------
# Alert firing — must not fire for past events, must fire for upcoming ones
# ---------------------------------------------------------------------------


class TestAlertsWithPastEvents:
    def test_no_alert_fired_for_past_helltide(self):
        """Alert must not fire for the -43 min helltide — it already happened."""
        # now=0, past event at -2580. Even if next_event returns it, the
        # alert condition (now < event.timestamp) should prevent firing.
        # But if next_event() is fixed, this is moot — test both paths.
        sched = AlertScheduler(now_fn=lambda: NOW)
        s = make_real_schedule()
        settings = make_settings()
        alerts = sched.check_alerts(s, settings)
        past_alerts = [a for a in alerts if a.timestamp < 0]
        assert (
            past_alerts == []
        ), f"Alerts fired for past events: {[(a.event_type, a.timestamp) for a in past_alerts]}"

    def test_upcoming_helltide_alert_fires_when_in_window(self):
        """Alert for +17 min helltide fires when now is within the 3-min lead window."""
        # Alert window: [1020 - 180, 1020) = [840, 1020)
        sched = AlertScheduler(now_fn=lambda: 900.0)
        s = make_real_schedule()
        settings = make_settings()
        alerts = sched.check_alerts(s, settings)
        ht_alerts = [a for a in alerts if a.event_type == EVENT_HELLTIDE]
        assert len(ht_alerts) == 1
        assert ht_alerts[0].timestamp == 1020

    def test_parse_schedule_with_past_timestamps(self):
        """parse_schedule() with real-shaped data preserves all events including past ones."""
        data = {
            "helltide": [
                {"timestamp": -2580},
                {"timestamp": 1020},
            ],
            "legion": [
                {"timestamp": -180},
                {"timestamp": 1320},
            ],
            "world_boss": [],
        }
        s = parse_schedule(data)
        assert len(s.helltide) == 2
        assert len(s.legion) == 2
        # next_event should skip the past ones
        assert s.next_event(EVENT_HELLTIDE, now=NOW).timestamp == 1020
        assert s.next_event(EVENT_LEGION, now=NOW).timestamp == 1320
