# Generated By: Claude Code (claude-sonnet-4-6)
"""Tests for d4_timer.settings module."""

import json

from d4_timer.config import (
    DEFAULT_ALERT_BG,
    DEFAULT_ALERT_FREQUENCY_HZ,
    DEFAULT_ALERT_MINUTES,
    DEFAULT_ENABLED,
    DEFAULT_WINDOW_BG,
)
from d4_timer.settings import Settings, load_settings, save_settings


class TestLoadSettings:
    def test_returns_defaults_when_file_missing(self, tmp_path):
        s = load_settings(tmp_path / "nonexistent.json")
        assert s.alert_minutes == DEFAULT_ALERT_MINUTES
        assert s.enabled == DEFAULT_ENABLED
        assert s.mute_all is False

    def test_returns_defaults_on_corrupt_json(self, tmp_path):
        p = tmp_path / "settings.json"
        p.write_text("{invalid json")
        s = load_settings(p)
        assert s.alert_minutes == DEFAULT_ALERT_MINUTES

    def test_returns_defaults_on_wrong_type(self, tmp_path):
        p = tmp_path / "settings.json"
        p.write_text("null")
        s = load_settings(p)
        assert s.alert_minutes == DEFAULT_ALERT_MINUTES

    def test_loads_valid_settings(self, tmp_path):
        p = tmp_path / "settings.json"
        data = {
            "alert_minutes": {"world_boss": 10, "helltide": 2, "legion": 1},
            "enabled": {"world_boss": False, "helltide": True, "legion": True},
            "mute_all": True,
        }
        p.write_text(json.dumps(data))
        s = load_settings(p)
        assert s.alert_minutes["world_boss"] == 10
        assert s.enabled["world_boss"] is False
        assert s.mute_all is True

    def test_ignores_invalid_alert_minutes_values(self, tmp_path):
        p = tmp_path / "settings.json"
        data = {"alert_minutes": {"world_boss": -1, "helltide": "bad", "legion": 0}}
        p.write_text(json.dumps(data))
        s = load_settings(p)
        # Falls back to defaults for invalid values
        assert s.alert_minutes["world_boss"] == DEFAULT_ALERT_MINUTES["world_boss"]
        assert s.alert_minutes["helltide"] == DEFAULT_ALERT_MINUTES["helltide"]

    def test_partial_settings_merged_with_defaults(self, tmp_path):
        p = tmp_path / "settings.json"
        data = {"alert_minutes": {"world_boss": 8}}
        p.write_text(json.dumps(data))
        s = load_settings(p)
        assert s.alert_minutes["world_boss"] == 8
        assert s.alert_minutes["helltide"] == DEFAULT_ALERT_MINUTES["helltide"]


class TestSaveSettings:
    def test_saves_and_reloads(self, tmp_path):
        p = tmp_path / "settings.json"
        s = Settings(
            alert_minutes={"world_boss": 7, "helltide": 4, "legion": 3},
            enabled={"world_boss": True, "helltide": False, "legion": True},
            mute_all=True,
        )
        save_settings(s, p)
        loaded = load_settings(p)
        assert loaded.alert_minutes["world_boss"] == 7
        assert loaded.enabled["helltide"] is False
        assert loaded.mute_all is True

    def test_creates_parent_directory(self, tmp_path):
        p = tmp_path / "nested" / "dir" / "settings.json"
        save_settings(Settings(), p)
        assert p.exists()

    def test_atomic_write_no_tmp_left_on_success(self, tmp_path):
        p = tmp_path / "settings.json"
        save_settings(Settings(), p)
        assert not (tmp_path / "settings.tmp").exists()

    def test_file_contains_valid_json(self, tmp_path):
        p = tmp_path / "settings.json"
        save_settings(Settings(), p)
        data = json.loads(p.read_text())
        assert "alert_minutes" in data
        assert "enabled" in data
        assert "mute_all" in data


class TestSettingsWindowFields:
    def test_defaults_have_window_bg(self):
        s = Settings()
        assert s.window_bg == DEFAULT_WINDOW_BG

    def test_defaults_have_none_position(self):
        s = Settings()
        assert s.window_x is None
        assert s.window_y is None

    def test_saves_and_loads_window_fields(self, tmp_path):
        p = tmp_path / "settings.json"
        s = Settings(window_bg="#ff0000", window_x=100, window_y=200)
        save_settings(s, p)
        loaded = load_settings(p)
        assert loaded.window_bg == "#ff0000"
        assert loaded.window_x == 100
        assert loaded.window_y == 200

    def test_invalid_bg_falls_back_to_default(self, tmp_path):
        p = tmp_path / "settings.json"
        p.write_text('{"window_bg": "notacolor"}')
        loaded = load_settings(p)
        assert loaded.window_bg == DEFAULT_WINDOW_BG

    def test_null_position_loads_as_none(self, tmp_path):
        p = tmp_path / "settings.json"
        p.write_text('{"window_x": null, "window_y": null}')
        loaded = load_settings(p)
        assert loaded.window_x is None
        assert loaded.window_y is None

    def test_defaults_alert_fields(self):
        s = Settings()
        assert s.alert_bg == DEFAULT_ALERT_BG
        assert s.alert_x is None
        assert s.alert_y is None
        assert s.alert_auto_dismiss is False

    def test_defaults_settings_position(self):
        s = Settings()
        assert s.settings_x is None
        assert s.settings_y is None

    def test_saves_and_loads_alert_fields(self, tmp_path):
        p = tmp_path / "settings.json"
        s = Settings(alert_bg="#001100", alert_x=50, alert_y=75, alert_auto_dismiss=True)
        save_settings(s, p)
        loaded = load_settings(p)
        assert loaded.alert_bg == "#001100"
        assert loaded.alert_x == 50
        assert loaded.alert_y == 75
        assert loaded.alert_auto_dismiss is True

    def test_saves_and_loads_settings_position(self, tmp_path):
        p = tmp_path / "settings.json"
        s = Settings(settings_x=300, settings_y=400)
        save_settings(s, p)
        loaded = load_settings(p)
        assert loaded.settings_x == 300
        assert loaded.settings_y == 400

    def test_invalid_alert_bg_falls_back_to_default(self, tmp_path):
        p = tmp_path / "settings.json"
        p.write_text('{"alert_bg": "badcolor"}')
        loaded = load_settings(p)
        assert loaded.alert_bg == DEFAULT_ALERT_BG

    def test_defaults_alert_frequency_hz(self):
        s = Settings()
        assert s.alert_frequency_hz == DEFAULT_ALERT_FREQUENCY_HZ

    def test_saves_and_loads_alert_frequency_hz(self, tmp_path):
        p = tmp_path / "settings.json"
        s = Settings(alert_frequency_hz=440)
        save_settings(s, p)
        loaded = load_settings(p)
        assert loaded.alert_frequency_hz == 440

    def test_invalid_freq_falls_back_to_default(self, tmp_path):
        p = tmp_path / "settings.json"
        p.write_text('{"alert_frequency_hz": 99999}')
        loaded = load_settings(p)
        assert loaded.alert_frequency_hz == DEFAULT_ALERT_FREQUENCY_HZ

    def test_freq_boundary_valid(self, tmp_path):
        p = tmp_path / "settings.json"
        p.write_text('{"alert_frequency_hz": 100}')
        loaded = load_settings(p)
        assert loaded.alert_frequency_hz == 100


class TestSettingsHelpers:
    def test_get_alert_minutes_present(self):
        s = Settings(alert_minutes={"world_boss": 9})
        assert s.get_alert_minutes("world_boss") == 9

    def test_get_alert_minutes_missing_uses_default(self):
        s = Settings(alert_minutes={})
        assert s.get_alert_minutes("world_boss") == DEFAULT_ALERT_MINUTES["world_boss"]

    def test_is_enabled_true(self):
        s = Settings(enabled={"world_boss": True})
        assert s.is_enabled("world_boss") is True

    def test_is_enabled_false(self):
        s = Settings(enabled={"world_boss": False})
        assert s.is_enabled("world_boss") is False

    def test_is_enabled_missing_defaults_true(self):
        s = Settings(enabled={})
        assert s.is_enabled("world_boss") is True
