# Generated By: Claude Code (claude-sonnet-4-6)
"""Tests for d4_timer.audio module."""

from unittest.mock import MagicMock, patch

import pytest

import d4_timer.audio as audio_module
from d4_timer.audio import generate_alert_sound, play_alert, reset_cache


@pytest.fixture(autouse=True)
def reset_audio_cache():
    """Reset module-level cache before each test."""
    reset_cache()
    yield
    reset_cache()


class TestGenerateAlertSound:
    def test_returns_sound_object_on_success(self):
        mock_pygame = MagicMock()
        mock_sndarray = MagicMock()
        mock_sound = MagicMock()
        mock_sndarray.make_sound.return_value = mock_sound
        mock_pygame.sndarray = mock_sndarray
        mock_pygame.mixer = MagicMock()

        with patch.dict("sys.modules", {"pygame": mock_pygame, "pygame.mixer": mock_pygame.mixer}):
            audio_module._initialized = True
            result = generate_alert_sound()

        assert result is mock_sound

    def test_caches_sound_on_second_call(self):
        mock_pygame = MagicMock()
        mock_sound = MagicMock()
        mock_pygame.sndarray.make_sound.return_value = mock_sound
        mock_pygame.mixer = MagicMock()

        with patch.dict("sys.modules", {"pygame": mock_pygame, "pygame.mixer": mock_pygame.mixer}):
            audio_module._initialized = True
            first = generate_alert_sound()
            second = generate_alert_sound()

        assert first is second
        # make_sound called only once
        assert mock_pygame.sndarray.make_sound.call_count == 1

    def test_returns_none_when_init_fails(self):
        with patch.object(audio_module, "_init_pygame", return_value=False):
            result = generate_alert_sound()
        assert result is None

    def test_returns_none_when_make_sound_raises(self):
        mock_pygame = MagicMock()
        mock_pygame.sndarray.make_sound.side_effect = Exception("boom")
        mock_pygame.mixer = MagicMock()

        with patch.dict("sys.modules", {"pygame": mock_pygame, "pygame.mixer": mock_pygame.mixer}):
            audio_module._initialized = True
            result = generate_alert_sound()

        assert result is None


class TestPlayAlert:
    def test_calls_play_on_sound(self):
        mock_sound = MagicMock()
        with patch.object(audio_module, "generate_alert_sound", return_value=mock_sound):
            play_alert()
        mock_sound.play.assert_called_once()

    def test_no_op_when_no_sound(self):
        with patch.object(audio_module, "generate_alert_sound", return_value=None):
            play_alert()  # Should not raise

    def test_no_op_when_play_raises(self):
        mock_sound = MagicMock()
        mock_sound.play.side_effect = Exception("audio error")
        with patch.object(audio_module, "generate_alert_sound", return_value=mock_sound):
            play_alert()  # Should not propagate exception


class TestResetCache:
    def test_clears_sound_cache(self):
        audio_module._sound_cache = MagicMock()
        audio_module._initialized = True
        reset_cache()
        assert audio_module._sound_cache is None
        assert audio_module._initialized is False
