# Generated By: Claude Code (claude-sonnet-4-6)
"""Tests for d4_timer.scheduler module."""

import pytest

from d4_timer.api import EventData, Schedule
from d4_timer.config import EVENT_HELLTIDE, EVENT_LEGION, EVENT_WORLD_BOSS
from d4_timer.scheduler import AlertScheduler
from d4_timer.settings import Settings


def make_schedule(wb_ts=None, ht_ts=None, leg_ts=None) -> Schedule:
    s = Schedule()
    if wb_ts is not None:
        s.world_boss.append(EventData(event_type=EVENT_WORLD_BOSS, timestamp=wb_ts))
    if ht_ts is not None:
        s.helltide.append(EventData(event_type=EVENT_HELLTIDE, timestamp=ht_ts))
    if leg_ts is not None:
        s.legion.append(EventData(event_type=EVENT_LEGION, timestamp=leg_ts))
    return s


def make_settings(
    wb_min=5, ht_min=3, leg_min=2, wb_en=True, ht_en=True, leg_en=True, mute=False
) -> Settings:
    return Settings(
        alert_minutes={
            EVENT_WORLD_BOSS: wb_min,
            EVENT_HELLTIDE: ht_min,
            EVENT_LEGION: leg_min,
        },
        enabled={
            EVENT_WORLD_BOSS: wb_en,
            EVENT_HELLTIDE: ht_en,
            EVENT_LEGION: leg_en,
        },
        mute_all=mute,
    )


class TestCountdown:
    def test_countdown_future(self):
        sched = AlertScheduler(now_fn=lambda: 1000.0)
        ev = EventData(event_type=EVENT_WORLD_BOSS, timestamp=4661)  # 3661 seconds away
        assert sched.countdown_str(ev) == "01:01:01"

    def test_countdown_past_shows_zero(self):
        sched = AlertScheduler(now_fn=lambda: 2000.0)
        ev = EventData(event_type=EVENT_WORLD_BOSS, timestamp=1000)
        assert sched.countdown_str(ev) == "00:00:00"

    def test_countdown_none_event(self):
        sched = AlertScheduler(now_fn=lambda: 1000.0)
        assert sched.countdown_str(None) == "--:--:--"

    def test_seconds_until_positive(self):
        sched = AlertScheduler(now_fn=lambda: 1000.0)
        ev = EventData(event_type=EVENT_WORLD_BOSS, timestamp=1100)
        assert sched.seconds_until(ev) == pytest.approx(100.0)

    def test_seconds_until_negative(self):
        sched = AlertScheduler(now_fn=lambda: 1200.0)
        ev = EventData(event_type=EVENT_WORLD_BOSS, timestamp=1100)
        assert sched.seconds_until(ev) == pytest.approx(-100.0)


class TestCheckAlerts:
    def _scheduler_at(self, now: float) -> AlertScheduler:
        return AlertScheduler(now_fn=lambda: now)

    def test_alert_fires_within_window(self):
        # Event at t=1000, alert lead = 5 min = 300s, so fires at t in [700, 1000)
        now = 750.0
        sched = self._scheduler_at(now)
        schedule = make_schedule(wb_ts=1000)
        settings = make_settings(wb_min=5)
        alerts = sched.check_alerts(schedule, settings)
        assert len(alerts) == 1
        assert alerts[0].event_type == EVENT_WORLD_BOSS

    def test_alert_does_not_fire_before_window(self):
        # now=600 is before the 700 alert window start
        sched = self._scheduler_at(600.0)
        schedule = make_schedule(wb_ts=1000)
        settings = make_settings(wb_min=5)
        alerts = sched.check_alerts(schedule, settings)
        assert alerts == []

    def test_alert_does_not_fire_after_event(self):
        # now=1001 is after the event
        sched = self._scheduler_at(1001.0)
        schedule = make_schedule(wb_ts=1000)
        settings = make_settings(wb_min=5)
        alerts = sched.check_alerts(schedule, settings)
        assert alerts == []

    def test_alert_fires_only_once(self):
        sched = self._scheduler_at(750.0)
        schedule = make_schedule(wb_ts=1000)
        settings = make_settings(wb_min=5)
        sched.check_alerts(schedule, settings)
        alerts2 = sched.check_alerts(schedule, settings)
        assert alerts2 == []

    def test_reset_fired_allows_refiring(self):
        sched = self._scheduler_at(750.0)
        schedule = make_schedule(wb_ts=1000)
        settings = make_settings(wb_min=5)
        sched.check_alerts(schedule, settings)
        sched.reset_fired()
        alerts2 = sched.check_alerts(schedule, settings)
        assert len(alerts2) == 1

    def test_disabled_event_no_alert(self):
        sched = self._scheduler_at(750.0)
        schedule = make_schedule(wb_ts=1000)
        settings = make_settings(wb_min=5, wb_en=False)
        alerts = sched.check_alerts(schedule, settings)
        assert alerts == []

    def test_multiple_events_all_fire(self):
        # All three events in their alert windows simultaneously
        sched = self._scheduler_at(950.0)
        schedule = make_schedule(wb_ts=1000, ht_ts=1000, leg_ts=1000)
        settings = make_settings(wb_min=5, ht_min=3, leg_min=2)
        alerts = sched.check_alerts(schedule, settings)
        event_types = {a.event_type for a in alerts}
        assert EVENT_WORLD_BOSS in event_types
        assert EVENT_HELLTIDE in event_types
        assert EVENT_LEGION in event_types

    def test_empty_schedule_no_alerts(self):
        sched = self._scheduler_at(750.0)
        schedule = Schedule()
        settings = make_settings()
        alerts = sched.check_alerts(schedule, settings)
        assert alerts == []

    def test_alert_at_exact_alert_time_boundary(self):
        # now == event.timestamp - alert_lead exactly
        # 1000 - 300 = 700; now=700 should fire
        sched = self._scheduler_at(700.0)
        schedule = make_schedule(wb_ts=1000)
        settings = make_settings(wb_min=5)
        alerts = sched.check_alerts(schedule, settings)
        assert len(alerts) == 1

    def test_alert_at_one_second_before_event(self):
        sched = self._scheduler_at(999.0)
        schedule = make_schedule(wb_ts=1000)
        settings = make_settings(wb_min=5)
        alerts = sched.check_alerts(schedule, settings)
        assert len(alerts) == 1


class TestHelltideDisplay:
    HELLTIDE_TS = 1000  # arbitrary start timestamp

    def _scheduler_at(self, now: float) -> AlertScheduler:
        return AlertScheduler(now_fn=lambda: now)

    def _make_ht_schedule(self, ts: int) -> Schedule:
        s = Schedule()
        s.helltide.append(EventData(event_type=EVENT_HELLTIDE, timestamp=ts))
        return s

    def test_active_within_window(self):
        # 100s into the 3300s helltide window
        now = self.HELLTIDE_TS + 100
        sched = self._scheduler_at(now)
        schedule = self._make_ht_schedule(self.HELLTIDE_TS)
        status, countdown = sched.helltide_display(schedule, now)
        assert status == "Active"
        # remaining = 3300 - 100 = 3200s = 0h 53m 20s
        assert countdown == "00:53:20"

    def test_inactive_before_start(self):
        # 500s before the helltide starts
        now = self.HELLTIDE_TS - 500
        sched = self._scheduler_at(now)
        schedule = self._make_ht_schedule(self.HELLTIDE_TS)
        status, countdown = sched.helltide_display(schedule, now)
        assert status == "Next"
        # seconds_until = 500 = 0h 8m 20s
        assert countdown == "00:08:20"

    def test_inactive_after_end(self):
        from d4_timer.config import HELLTIDE_DURATION_SECONDS

        # Past the end of the only helltide event
        now = self.HELLTIDE_TS + HELLTIDE_DURATION_SECONDS + 100
        sched = self._scheduler_at(now)
        schedule = self._make_ht_schedule(self.HELLTIDE_TS)
        status, countdown = sched.helltide_display(schedule, now)
        assert status == "Next"
        assert countdown == "--:--:--"  # no future events

    def test_active_at_exact_start(self):
        now = float(self.HELLTIDE_TS)
        sched = self._scheduler_at(now)
        schedule = self._make_ht_schedule(self.HELLTIDE_TS)
        status, _ = sched.helltide_display(schedule, now)
        assert status == "Active"

    def test_empty_schedule_returns_next(self):
        sched = self._scheduler_at(1000.0)
        schedule = Schedule()
        status, countdown = sched.helltide_display(schedule, 1000.0)
        assert status == "Next"
        assert countdown == "--:--:--"
