# Generated By: Claude Code (claude-sonnet-4-6)
"""Tests for d4_timer.audio module."""

from unittest.mock import MagicMock, patch

import pytest

import d4_timer.audio as audio_module
from d4_timer.audio import generate_alert_sound, play_alert, reset_cache


@pytest.fixture(autouse=True)
def reset_audio_cache():
    """Reset module-level cache before each test."""
    reset_cache()
    yield
    reset_cache()


def _make_mock_pygame(sound: MagicMock | None = None) -> MagicMock:
    """Return a mock pygame with mixer.get_init() → (44100, -16, 2) and Sound()."""
    mock_pygame = MagicMock()
    mock_pygame.mixer.get_init.return_value = (44100, -16, 2)
    mock_pygame.mixer.Sound.return_value = sound or MagicMock()
    return mock_pygame


class TestGenerateAlertSound:
    def test_returns_sound_object_on_success(self):
        mock_sound = MagicMock()
        mock_pygame = _make_mock_pygame(mock_sound)

        with patch.object(audio_module, "pygame", mock_pygame):
            audio_module._initialized = True
            result = generate_alert_sound()

        assert result is mock_sound

    def test_caches_sound_on_second_call(self):
        mock_sound = MagicMock()
        mock_pygame = _make_mock_pygame(mock_sound)

        with patch.object(audio_module, "pygame", mock_pygame):
            audio_module._initialized = True
            first = generate_alert_sound()
            second = generate_alert_sound()

        assert first is second
        # Sound() constructed only once
        assert mock_pygame.mixer.Sound.call_count == 1

    def test_returns_none_when_init_fails(self):
        with patch.object(audio_module, "_init_pygame", return_value=False):
            result = generate_alert_sound()
        assert result is None

    def test_returns_none_when_make_sound_raises(self):
        mock_pygame = _make_mock_pygame()
        mock_pygame.mixer.Sound.side_effect = Exception("boom")

        with patch.object(audio_module, "pygame", mock_pygame):
            audio_module._initialized = True
            result = generate_alert_sound()

        assert result is None


class TestPlayAlert:
    def test_calls_play_on_sound(self):
        mock_sound = MagicMock()
        with patch.object(audio_module, "generate_alert_sound", return_value=mock_sound):
            play_alert()
        mock_sound.play.assert_called_once()

    def test_no_op_when_no_sound(self):
        with patch.object(audio_module, "generate_alert_sound", return_value=None):
            play_alert()  # Should not raise

    def test_no_op_when_play_raises(self):
        mock_sound = MagicMock()
        mock_sound.play.side_effect = Exception("audio error")
        with patch.object(audio_module, "generate_alert_sound", return_value=mock_sound):
            play_alert()  # Should not propagate exception


class TestResetCache:
    def test_clears_sound_cache(self):
        audio_module._sound_cache = MagicMock()
        audio_module._initialized = True
        reset_cache()
        assert audio_module._sound_cache is None
        assert audio_module._initialized is False


class TestInitPygame:
    def test_success_sets_initialized(self):
        mock_pygame = MagicMock()
        with patch.object(audio_module, "pygame", mock_pygame):
            result = audio_module._init_pygame()
        assert result is True
        assert audio_module._initialized is True
        mock_pygame.mixer.pre_init.assert_called_once()
        mock_pygame.mixer.init.assert_called_once()

    def test_failure_returns_false(self):
        mock_pygame = MagicMock()
        mock_pygame.mixer.init.side_effect = Exception("no audio device")
        with patch.object(audio_module, "pygame", mock_pygame):
            result = audio_module._init_pygame()
        assert result is False
        assert audio_module._initialized is False

    def test_returns_true_immediately_if_already_initialized(self):
        audio_module._initialized = True
        mock_pygame = MagicMock()
        with patch.object(audio_module, "pygame", mock_pygame):
            result = audio_module._init_pygame()
        assert result is True
        mock_pygame.mixer.init.assert_not_called()
