# Generated By: Claude Code (claude-sonnet-4-6)
"""Entry point: python -m d4_timer [--debug] [--quiet]"""

import argparse
import logging


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="d4_timer",
        description="Diablo 4 event tracker — system tray app for Windows 11",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable DEBUG-level logging to stdout",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress audio alerts (popups still appear)",
    )
    args = parser.parse_args()

    level = logging.DEBUG if args.debug else logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(asctime)s %(name)s %(levelname)s %(message)s",
    )

    from .controller import AppController

    app = AppController(debug=args.debug, quiet=args.quiet)
    app.run()


if __name__ == "__main__":
    main()
