# Generated By: Claude Code (claude-sonnet-4-6)
"""API client for helltides.com schedule endpoint."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Optional

import requests

from .config import (
    API_TIMEOUT_SECONDS,
    API_URL,
    EVENT_HELLTIDE,
    EVENT_LEGION,
    EVENT_WORLD_BOSS,
)

log = logging.getLogger(__name__)


@dataclass
class EventData:
    """A single upcoming event occurrence."""

    event_type: str
    timestamp: int           # Unix epoch seconds
    boss_name: Optional[str] = None    # World Boss only
    zone_name: Optional[str] = None    # World Boss only


@dataclass
class Schedule:
    """Parsed schedule containing upcoming events for each type."""

    world_boss: list[EventData] = field(default_factory=list)
    helltide: list[EventData] = field(default_factory=list)
    legion: list[EventData] = field(default_factory=list)

    def by_type(self, event_type: str) -> list[EventData]:
        return getattr(self, event_type, [])

    def next_event(self, event_type: str) -> Optional[EventData]:
        events = self.by_type(event_type)
        return events[0] if events else None


def fetch_schedule(url: str = API_URL) -> dict:
    """Fetch raw schedule JSON from the API. Raises on failure."""
    response = requests.get(url, timeout=API_TIMEOUT_SECONDS)
    response.raise_for_status()
    return response.json()


def parse_schedule(data: dict) -> Schedule:
    """Parse raw API response dict into a Schedule."""
    schedule = Schedule()

    raw_world_boss = data.get(EVENT_WORLD_BOSS) or []
    for item in raw_world_boss:
        ts = item.get("timestamp")
        if ts is None:
            continue
        zones = item.get("zone") or []
        zone_name = zones[0].get("name") if zones else None
        schedule.world_boss.append(
            EventData(
                event_type=EVENT_WORLD_BOSS,
                timestamp=int(ts),
                boss_name=item.get("boss"),
                zone_name=zone_name,
            )
        )

    raw_helltide = data.get(EVENT_HELLTIDE) or []
    for item in raw_helltide:
        ts = item.get("timestamp")
        if ts is None:
            continue
        schedule.helltide.append(
            EventData(
                event_type=EVENT_HELLTIDE,
                timestamp=int(ts),
            )
        )

    raw_legion = data.get(EVENT_LEGION) or []
    for item in raw_legion:
        ts = item.get("timestamp")
        if ts is None:
            continue
        schedule.legion.append(
            EventData(
                event_type=EVENT_LEGION,
                timestamp=int(ts),
            )
        )

    return schedule
