# Generated By: Claude Code (claude-sonnet-4-6)
"""Audio alert via programmatic sine wave generation using pygame.mixer."""

from __future__ import annotations

import array
import logging
import math
import pygame
from typing import Any, Optional

from .config import (
    AUDIO_DURATION_MS,
    AUDIO_FREQUENCY_HZ,
    AUDIO_SAMPLE_RATE,
    AUDIO_VOLUME,
)

log = logging.getLogger(__name__)

_sound_cache: Optional[Any] = None
_cached_frequency: int = 0
_initialized: bool = False


def _init_pygame() -> bool:
    """Initialize pygame mixer. Returns True on success."""
    global _initialized
    if _initialized:
        return True
    try:
        pygame.mixer.pre_init(
            frequency=AUDIO_SAMPLE_RATE,
            size=-16,
            channels=1,
            buffer=512,
        )
        pygame.mixer.init()
        _initialized = True
        return True
    except Exception:
        log.exception("Failed to initialize pygame.mixer")
        return False


def generate_alert_sound(frequency_hz: int = AUDIO_FREQUENCY_HZ) -> Optional[Any]:
    """Build and cache a pygame Sound object (sine wave). Returns None on failure."""
    global _sound_cache, _cached_frequency
    if _sound_cache is not None and _cached_frequency == frequency_hz:
        return _sound_cache

    if not _init_pygame():
        return None

    try:
        # Use actual post-init settings — pre_init values are hints, not guarantees
        freq, _size, channels = pygame.mixer.get_init()
        num_samples = int(freq * AUDIO_DURATION_MS / 1000)
        max_amplitude = int(32767 * AUDIO_VOLUME)

        # Build interleaved buffer for mono or stereo without numpy dependency
        buf = array.array("h", [0] * num_samples * channels)
        for i in range(num_samples):
            t = i / freq
            # Fade out over last 10% of duration to avoid click
            fade = 1.0 - max(0.0, (i - num_samples * 0.9) / (num_samples * 0.1))
            val = int(max_amplitude * math.sin(2 * math.pi * frequency_hz * t) * fade)
            for ch in range(channels):
                buf[i * channels + ch] = val

        sound = pygame.mixer.Sound(buffer=buf)
        _sound_cache = sound
        _cached_frequency = frequency_hz
        return sound
    except Exception:
        log.exception("Failed to generate alert sound")
        return None


def play_alert(frequency_hz: int = AUDIO_FREQUENCY_HZ) -> None:
    """Play the alert sound. No-op if pygame is unavailable or sound fails."""
    sound = generate_alert_sound(frequency_hz)
    if sound is None:
        return
    try:
        sound.play()
    except Exception:
        log.exception("Failed to play alert sound")


def reset_cache() -> None:
    """Reset cached sound and init state — for testing."""
    global _sound_cache, _cached_frequency, _initialized
    _sound_cache = None
    _cached_frequency = 0
    _initialized = False
