# Generated By: Claude Code (claude-sonnet-4-6)
"""Audio alert via programmatic sine wave generation using pygame.mixer."""

from __future__ import annotations

import array
import logging
import math
from typing import Optional

from .config import (
    AUDIO_DURATION_MS,
    AUDIO_FREQUENCY_HZ,
    AUDIO_SAMPLE_RATE,
    AUDIO_VOLUME,
)

log = logging.getLogger(__name__)

_sound_cache: Optional[object] = None
_initialized: bool = False


def _init_pygame() -> bool:
    """Initialize pygame mixer. Returns True on success."""
    global _initialized
    if _initialized:
        return True
    try:
        import pygame
        pygame.mixer.pre_init(
            frequency=AUDIO_SAMPLE_RATE,
            size=-16,
            channels=1,
            buffer=512,
        )
        pygame.mixer.init()
        _initialized = True
        return True
    except Exception:
        log.exception("Failed to initialize pygame.mixer")
        return False


def generate_alert_sound() -> Optional[object]:
    """Build and cache a pygame Sound object (sine wave). Returns None on failure."""
    global _sound_cache
    if _sound_cache is not None:
        return _sound_cache

    if not _init_pygame():
        return None

    try:
        import pygame

        num_samples = int(AUDIO_SAMPLE_RATE * AUDIO_DURATION_MS / 1000)
        max_amplitude = int(32767 * AUDIO_VOLUME)

        samples = array.array("h", [0] * num_samples)
        for i in range(num_samples):
            t = i / AUDIO_SAMPLE_RATE
            # Fade out over last 10% of duration to avoid click
            fade = 1.0 - max(0.0, (i - num_samples * 0.9) / (num_samples * 0.1))
            samples[i] = int(
                max_amplitude * math.sin(2 * math.pi * AUDIO_FREQUENCY_HZ * t) * fade
            )

        sound = pygame.sndarray.make_sound(samples)
        _sound_cache = sound
        return sound
    except Exception:
        log.exception("Failed to generate alert sound")
        return None


def play_alert() -> None:
    """Play the alert sound. No-op if pygame is unavailable or sound fails."""
    sound = generate_alert_sound()
    if sound is None:
        return
    try:
        sound.play()
    except Exception:
        log.exception("Failed to play alert sound")


def reset_cache() -> None:
    """Reset cached sound and init state — for testing."""
    global _sound_cache, _initialized
    _sound_cache = None
    _initialized = False
