# Generated By: Claude Code (claude-sonnet-4-6)
"""All constants and defaults — single source of truth."""

# API
API_URL = "https://helltides.com/api/schedule"
API_POLL_INTERVAL_SECONDS = 60
API_BACKOFF_MAX_SECONDS = 300  # 5 minutes
API_BACKOFF_BASE_SECONDS = 5
API_TIMEOUT_SECONDS = 10

# Event types
EVENT_WORLD_BOSS = "world_boss"
EVENT_HELLTIDE = "helltide"
EVENT_LEGION = "legion"
ALL_EVENT_TYPES = (EVENT_WORLD_BOSS, EVENT_HELLTIDE, EVENT_LEGION)

# Display names
EVENT_DISPLAY_NAMES = {
    EVENT_WORLD_BOSS: "World Boss",
    EVENT_HELLTIDE: "Helltide",
    EVENT_LEGION: "Legion",
}

# Default alert lead times in minutes
DEFAULT_ALERT_MINUTES = {
    EVENT_WORLD_BOSS: 5,
    EVENT_HELLTIDE: 3,
    EVENT_LEGION: 2,
}

# Default enabled state
DEFAULT_ENABLED = {
    EVENT_WORLD_BOSS: True,
    EVENT_HELLTIDE: True,
    EVENT_LEGION: True,
}

# Settings
SETTINGS_DIR_NAME = "d4-timer"
SETTINGS_FILE_NAME = "settings.json"

# UI
TICK_INTERVAL_MS = 1000
MAIN_WINDOW_TITLE = "D4 Timer"
ALERT_WINDOW_TITLE = "D4 Event Alert"
ALERT_AUTO_DISMISS_MS = 10_000  # 10 seconds
MAIN_WINDOW_WIDTH = 320
MAIN_WINDOW_HEIGHT = 180

# Tray icon
TRAY_ICON_NAME = "D4 Timer"
TRAY_ICON_SIZE = (64, 64)
TRAY_ICON_COLOR_ACTIVE = "#8B0000"   # dark crimson
TRAY_ICON_COLOR_MUTED = "#555555"    # gray

# Audio
AUDIO_SAMPLE_RATE = 44100
AUDIO_FREQUENCY_HZ = 880
AUDIO_DURATION_MS = 400
AUDIO_VOLUME = 0.6
