# Generated By: Claude Code (claude-sonnet-4-6)
"""All constants and defaults — single source of truth."""

# API
API_URL = "https://helltides.com/api/schedule"
API_POLL_INTERVAL_SECONDS = 600  # 10 minutes; countdowns calculated from cached data
API_BACKOFF_MAX_SECONDS = 300  # 5 minutes
API_BACKOFF_BASE_SECONDS = 5
API_TIMEOUT_SECONDS = 10

# Event types
EVENT_WORLD_BOSS = "world_boss"
EVENT_HELLTIDE = "helltide"
EVENT_LEGION = "legion"
ALL_EVENT_TYPES = (EVENT_WORLD_BOSS, EVENT_HELLTIDE, EVENT_LEGION)

# Display names
EVENT_DISPLAY_NAMES = {
    EVENT_WORLD_BOSS: "World Boss",
    EVENT_HELLTIDE: "Helltide",
    EVENT_LEGION: "Legion",
}

# Alert lead time bounds (minutes)
MIN_ALERT_MINUTES = 1
MAX_ALERT_MINUTES = 240

# Default alert lead times in minutes
DEFAULT_ALERT_MINUTES = {
    EVENT_WORLD_BOSS: 5,
    EVENT_HELLTIDE: 3,
    EVENT_LEGION: 2,
}

# Default enabled state
DEFAULT_ENABLED = {
    EVENT_WORLD_BOSS: True,
    EVENT_HELLTIDE: True,
    EVENT_LEGION: True,
}

# Settings
SETTINGS_DIR_NAME = "d4-timer"
SETTINGS_FILE_NAME = "settings.json"

# UI
TICK_INTERVAL_MS = 1000
ALERT_WINDOW_TITLE = "D4 Event Alert"
ALERT_AUTO_DISMISS_MS = 10_000  # 10 seconds
DEFAULT_WINDOW_BG = "#1a1a1a"
DEFAULT_ALERT_BG = "#2d0000"

# Helltide is active for 55 minutes after its start timestamp
HELLTIDE_DURATION_SECONDS = 55 * 60

# Diablo IV process detection
DIABLO_PROCESS_NAME = "Diablo IV.exe"
PROCESS_CHECK_INTERVAL_SECONDS = 15

# Tray icon
TRAY_ICON_NAME = "D4 Timer"
TRAY_ICON_SIZE = (64, 64)
TRAY_ICON_COLOR_ACTIVE = "#609755"
TRAY_ICON_COLOR_MUTED = "#555555"

# Window border mirrors tray icon color
WINDOW_BORDER_NORMAL = TRAY_ICON_COLOR_ACTIVE
WINDOW_BORDER_SUPPRESSED = TRAY_ICON_COLOR_MUTED

# Audio
AUDIO_SAMPLE_RATE = 44100
AUDIO_FREQUENCY_HZ = 880
AUDIO_DURATION_MS = 400
AUDIO_VOLUME = 0.6
DEFAULT_ALERT_FREQUENCY_HZ = AUDIO_FREQUENCY_HZ
MIN_ALERT_FREQUENCY_HZ = 100
MAX_ALERT_FREQUENCY_HZ = 8000
