# Generated By: Claude Code (claude-sonnet-4-6)
"""AppController: orchestrates threads, tkinter mainloop, and all subsystems."""

from __future__ import annotations

import logging
import subprocess
import threading
import time
from typing import Any

from .api import EventData, Schedule, fetch_schedule, parse_schedule
from .audio import generate_alert_sound, play_alert
from .config import (
    ALL_EVENT_TYPES,
    API_BACKOFF_MAX_SECONDS,
    API_POLL_INTERVAL_SECONDS,
    DIABLO_PROCESS_NAME,
    EVENT_DISPLAY_NAMES,
    EVENT_HELLTIDE,
    EVENT_WORLD_BOSS,
    PROCESS_CHECK_INTERVAL_SECONDS,
    TICK_INTERVAL_MS,
)
from .scheduler import AlertScheduler
from .settings import Settings, load_settings, save_settings
from .startup import set_run_on_startup
from .tray import create_tray_icon, generate_icon_image
from .ui.alert_window import AlertWindow
from .ui.main_window import MainWindow
from .ui.settings_window import SettingsWindow

log = logging.getLogger(__name__)


def _is_process_running(name: str) -> bool:
    """Return True if a process with the given image name is currently running."""
    try:
        out = subprocess.run(
            ["tasklist", "/FI", f"IMAGENAME eq {name}", "/NH"],
            capture_output=True,
            text=True,
            timeout=3,
            creationflags=subprocess.CREATE_NO_WINDOW,
        ).stdout
        return name.lower() in out.lower()
    except Exception:
        return False


class AppController:
    """Top-level coordinator for the D4 Timer application."""

    def __init__(self, debug: bool = False, quiet: bool = False):
        self._debug = debug
        self._quiet = quiet

        self._settings: Settings = load_settings()
        self._schedule: Schedule = Schedule()
        self._schedule_lock = threading.Lock()
        self._stop_event = threading.Event()

        self._scheduler = AlertScheduler()

        # tkinter root
        import tkinter as tk

        self._root = tk.Tk()
        self._root.withdraw()

        # UI
        self._main_window = MainWindow(self._root, self, self._settings)
        self._tray_icon: Any = None
        self._settings_window: SettingsWindow | None = None

        # Process detection state — None until first check so first result always triggers update
        self._game_running: bool | None = None
        self._last_process_check: float = 0.0

    # ------------------------------------------------------------------
    # Public API (called from UI or tray)
    # ------------------------------------------------------------------

    def toggle_mute(self) -> None:
        self._settings.mute_all = not self._settings.mute_all
        save_settings(self._settings)
        self._update_tray_icon()
        log.debug("Mute toggled: %s", self._settings.mute_all)

    def open_settings(self) -> None:
        def _on_save(new_settings: Settings) -> None:
            old_alert = self._settings.alert_minutes
            old_enabled = dict(self._settings.enabled)
            self._settings = new_settings
            if new_settings.alert_minutes != old_alert:
                self._scheduler.reset_fired()
            save_settings(self._settings)
            set_run_on_startup(new_settings.run_on_startup)
            self._main_window.apply_bg(new_settings.window_bg)
            for et in ALL_EVENT_TYPES:
                if old_enabled.get(et) != new_settings.enabled.get(et):
                    self._main_window.set_event_visible(et, new_settings.is_enabled(et))

        def _on_settings_pos(x: int, y: int) -> None:
            self._settings.settings_x = x
            self._settings.settings_y = y
            save_settings(self._settings)

        if self._settings_window is None:
            self._settings_window = SettingsWindow(
                self._root, self._settings, _on_save, _on_settings_pos
            )
        self._settings_window._settings = self._settings
        self._settings_window.show()

    def show_main_window(self) -> None:
        self._main_window.show()

    def test_alert(self) -> None:
        """Play audio and show an AlertWindow for the soonest upcoming event."""
        with self._schedule_lock:
            schedule = self._schedule
        now = time.time()

        soonest: EventData | None = None
        for event_type in ALL_EVENT_TYPES:
            event = schedule.next_event(event_type, now=now)
            if event is not None:
                if soonest is None or event.timestamp < soonest.timestamp:
                    soonest = event

        if soonest is None:
            soonest = EventData(
                event_type=EVENT_WORLD_BOSS,
                timestamp=int(now) + 60,
            )

        if not self._quiet and not self._settings.mute_all:
            play_alert(self._settings.alert_frequency_hz)
        AlertWindow(self._root, soonest, self._settings, self._save_alert_pos).show()

    def toggle_event(self, event_type: str) -> None:
        """Flip the enabled state for an event type and update the main window."""
        current = self._settings.enabled.get(event_type, True)
        self._settings.enabled[event_type] = not current
        save_settings(self._settings)
        self._main_window.set_event_visible(event_type, self._settings.enabled[event_type])

    def is_event_enabled(self, event_type: str) -> bool:
        return self._settings.is_enabled(event_type)

    def is_muted(self) -> bool:
        return self._settings.mute_all

    def is_game_suppressed(self) -> bool:
        return self._settings.suppress_when_not_gaming and not self._game_running

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def run(self) -> None:
        """Start all threads and enter the tkinter mainloop."""
        set_run_on_startup(self._settings.run_on_startup)  # keep registry in sync with settings
        threading.Thread(target=generate_alert_sound, daemon=True, name="audio-prewarm").start()

        def _schedule_toggle(et: str) -> None:
            self._root.after(0, self.toggle_event, et)

        self._tray_icon = create_tray_icon(
            on_click=lambda icon, item: self._root.after(0, self.show_main_window),
            on_quit=lambda icon, item: self._root.after(0, self._quit),
            on_toggle_mute=lambda icon, item: self._root.after(0, self.toggle_mute),
            on_settings=lambda icon, item: self._root.after(0, self.open_settings),
            on_test_alert=lambda icon, item: self._root.after(0, self.test_alert),
            on_toggle_event=_schedule_toggle,
            is_event_enabled=self.is_event_enabled,
            is_muted=self.is_muted,
        )
        self._update_tray_icon()  # apply correct initial color before tray thread starts

        poll_thread = threading.Thread(target=self._poll_loop, daemon=True, name="api-poll")
        poll_thread.start()

        tray_thread = threading.Thread(target=self._tray_icon.run, daemon=True, name="tray")
        tray_thread.start()

        self._root.after(TICK_INTERVAL_MS, self._tick)
        self._root.mainloop()

        self._stop_event.set()
        if self._tray_icon:
            try:
                self._tray_icon.stop()
            except Exception:
                pass

    def _quit(self) -> None:
        self._stop_event.set()
        if self._tray_icon:
            try:
                self._tray_icon.stop()
            except Exception:
                pass
        self._root.destroy()

    # ------------------------------------------------------------------
    # Tick — runs on main thread every second
    # ------------------------------------------------------------------

    def _tick(self) -> None:
        with self._schedule_lock:
            schedule = self._schedule
        now = time.time()

        countdowns: dict[str, str] = {}
        label_updates: dict[str, str] = {}

        for event_type in ALL_EVENT_TYPES:
            if event_type == EVENT_HELLTIDE:
                status, ht_str = self._scheduler.helltide_display(schedule, now)
                countdowns[event_type] = ht_str
                if status == "Active":
                    label_updates[event_type] = EVENT_DISPLAY_NAMES[event_type] + " (Active)"
            else:
                event = schedule.next_event(event_type)
                countdowns[event_type] = self._scheduler.countdown_str(event)

        self._main_window.update_countdowns(countdowns, label_updates if label_updates else None)

        # Process detection — throttled, only when suppression is enabled
        if self._settings.suppress_when_not_gaming:
            if now - self._last_process_check >= PROCESS_CHECK_INTERVAL_SECONDS:
                prev = self._game_running
                self._game_running = _is_process_running(DIABLO_PROCESS_NAME)
                self._last_process_check = now
                if self._game_running != prev:
                    log.info(
                        "Game process %s: %s",
                        DIABLO_PROCESS_NAME,
                        "is running" if self._game_running else "not running",
                    )
                    self._update_tray_icon()

        game_suppressed = self._settings.suppress_when_not_gaming and not self._game_running
        self._main_window.update_status(self._settings.mute_all, game_suppressed)

        # Check alerts — skip entirely when suppressed so events aren't marked fired
        if not self._settings.mute_all:
            game_suppressed = self._settings.suppress_when_not_gaming and not self._game_running
            if not game_suppressed:
                alerts = self._scheduler.check_alerts(schedule, self._settings)
                for event in alerts:
                    log.debug(
                        "Dispatching alert: %s | alert_minutes=%s | enabled=%s"
                        " | mute_all=%s | freq_hz=%d",
                        event.event_type,
                        self._settings.alert_minutes,
                        self._settings.enabled,
                        self._settings.mute_all,
                        self._settings.alert_frequency_hz,
                    )
                    if not self._quiet:
                        play_alert(self._settings.alert_frequency_hz)
                    AlertWindow(self._root, event, self._settings, self._save_alert_pos).show()
                    log.info("Alert fired for %s at %s", event.event_type, event.timestamp)

        self._root.after(TICK_INTERVAL_MS, self._tick)

    # ------------------------------------------------------------------
    # API poll loop — background daemon thread
    # ------------------------------------------------------------------

    def _poll_loop(self) -> None:
        backoff = API_POLL_INTERVAL_SECONDS
        while not self._stop_event.is_set():
            try:
                data = fetch_schedule()
                parsed = parse_schedule(data)
                with self._schedule_lock:
                    self._schedule = parsed
                log.debug(
                    "Schedule updated: %d WB, %d HT, %d LEG",
                    len(parsed.world_boss),
                    len(parsed.helltide),
                    len(parsed.legion),
                )
                backoff = API_POLL_INTERVAL_SECONDS
            except Exception:
                log.warning("API fetch failed; retrying in %ss", backoff)
                backoff = min(backoff * 2, API_BACKOFF_MAX_SECONDS)

            self._stop_event.wait(timeout=backoff)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _save_alert_pos(self) -> None:
        save_settings(self._settings)

    def _update_tray_icon(self) -> None:
        if self._tray_icon:
            try:
                self._tray_icon.icon = generate_icon_image(
                    muted=self._settings.mute_all or self.is_game_suppressed()
                )
            except Exception:
                pass
