# Generated By: Claude Code (claude-sonnet-4-6)
"""Alert scheduling: countdown calculation and deduplication."""

from __future__ import annotations

import time
from typing import Callable, Optional

from .api import EventData, Schedule
from .config import ALL_EVENT_TYPES
from .settings import Settings


class AlertScheduler:
    """Determines when alerts should fire and deduplicates them."""

    def __init__(self, now_fn: Callable[[], float] = time.time):
        self._now_fn = now_fn
        # Keyed by (event_type, timestamp) — ephemeral, cleared on alert_minutes change
        self._fired: set[tuple[str, int]] = set()

    def reset_fired(self) -> None:
        """Clear the fired set — call when alert_minutes changes."""
        self._fired.clear()

    def seconds_until(self, event: EventData) -> float:
        """Seconds remaining until the event starts (negative if past)."""
        return event.timestamp - self._now_fn()

    def countdown_str(self, event: Optional[EventData]) -> str:
        """Human-readable HH:MM:SS countdown, or '--:--:--' if no event."""
        if event is None:
            return "--:--:--"
        remaining = int(self.seconds_until(event))
        if remaining < 0:
            return "00:00:00"
        hours, rem = divmod(remaining, 3600)
        minutes, seconds = divmod(rem, 60)
        return f"{hours:02d}:{minutes:02d}:{seconds:02d}"

    def check_alerts(
        self, schedule: Schedule, settings: Settings
    ) -> list[EventData]:
        """Return events that should fire an alert right now."""
        alerts: list[EventData] = []
        now = self._now_fn()

        for event_type in ALL_EVENT_TYPES:
            if not settings.is_enabled(event_type):
                continue

            event = schedule.next_event(event_type)
            if event is None:
                continue

            alert_lead = settings.get_alert_minutes(event_type) * 60
            key = (event_type, event.timestamp)

            alert_time = event.timestamp - alert_lead
            if alert_time <= now < event.timestamp and key not in self._fired:
                self._fired.add(key)
                alerts.append(event)

        return alerts
