# Generated By: Claude Code (claude-sonnet-4-6)
"""Alert scheduling: countdown calculation and deduplication."""

from __future__ import annotations

import logging
import time
from typing import Callable

from .api import EventData, Schedule
from .config import ALL_EVENT_TYPES, EVENT_HELLTIDE, HELLTIDE_DURATION_SECONDS
from .settings import Settings

log = logging.getLogger(__name__)


def _ts(epoch: float) -> str:
    """Format epoch seconds as local HH:MM:SS for log readability."""
    return time.strftime("%H:%M:%S", time.localtime(epoch))


class AlertScheduler:
    """Determines when alerts should fire and deduplicates them."""

    def __init__(self, now_fn: Callable[[], float] = time.time):
        self._now_fn = now_fn
        # Keyed by (event_type, timestamp) — ephemeral, cleared on alert_minutes change
        self._fired: set[tuple[str, int]] = set()

    def reset_fired(self) -> None:
        """Clear the fired set — call when alert_minutes changes."""
        self._fired.clear()

    def seconds_until(self, event: EventData) -> float:
        """Seconds remaining until the event starts (negative if past)."""
        return event.timestamp - self._now_fn()

    def countdown_str(self, event: EventData | None) -> str:
        """Human-readable HH:MM:SS countdown, or '--:--:--' if no event."""
        if event is None:
            return "--:--:--"
        remaining = int(self.seconds_until(event))
        if remaining < 0:
            return "00:00:00"
        hours, rem = divmod(remaining, 3600)
        minutes, seconds = divmod(rem, 60)
        return f"{hours:02d}:{minutes:02d}:{seconds:02d}"

    def helltide_display(self, schedule: Schedule, now: float | None = None) -> tuple[str, str]:
        """Return (status, countdown) for helltide.

        status is 'Active' if a helltide is running, 'Next' otherwise.
        countdown is time until end (Active) or until next start (Next).
        """
        if now is None:
            now = self._now_fn()

        events = schedule.by_type(EVENT_HELLTIDE)

        # Find the most recently started helltide (largest timestamp <= now)
        recent = None
        for event in events:
            if event.timestamp <= now:
                if recent is None or event.timestamp > recent.timestamp:
                    recent = event

        if recent is not None:
            end_time = recent.timestamp + HELLTIDE_DURATION_SECONDS
            if now < end_time:
                remaining = int(end_time - now)
                hours, rem = divmod(remaining, 3600)
                minutes, seconds = divmod(rem, 60)
                return ("Active", f"{hours:02d}:{minutes:02d}:{seconds:02d}")

        next_event = schedule.next_event(EVENT_HELLTIDE, now=now)
        return ("Next", self.countdown_str(next_event))

    def check_alerts(self, schedule: Schedule, settings: Settings) -> list[EventData]:
        """Return events that should fire an alert right now."""
        alerts: list[EventData] = []
        now = self._now_fn()

        # Prune entries for events that have already started — they can never re-fire
        self._fired = {key for key in self._fired if key[1] > now}

        for event_type in ALL_EVENT_TYPES:
            if not settings.is_enabled(event_type):
                continue

            event = schedule.next_event(event_type, now=now)
            if event is None:
                continue

            alert_minutes = settings.get_alert_minutes(event_type)
            alert_lead = alert_minutes * 60
            alert_time = event.timestamp - alert_lead
            countdown = event.timestamp - now
            key = (event_type, event.timestamp)

            if alert_time <= now < event.timestamp and key not in self._fired:
                self._fired.add(key)
                log.info(
                    "Alert FIRED: %-12s | event@%s | alert_minutes=%d"
                    " | countdown_at_fire=%.2fmin | expected<=%.2fmin | delta=%.2fmin",
                    event_type,
                    _ts(event.timestamp),
                    alert_minutes,
                    countdown / 60,
                    alert_minutes,
                    alert_minutes - countdown / 60,
                )
                alerts.append(event)

        return alerts
