# Generated By: Claude Code (claude-sonnet-4-6)
"""User settings persistence to %APPDATA%\\d4-timer\\settings.json."""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict

from .config import (
    ALL_EVENT_TYPES,
    DEFAULT_ALERT_BG,
    DEFAULT_ALERT_FREQUENCY_HZ,
    DEFAULT_ALERT_MINUTES,
    DEFAULT_ENABLED,
    DEFAULT_WINDOW_BG,
    MAX_ALERT_FREQUENCY_HZ,
    MAX_ALERT_MINUTES,
    MIN_ALERT_FREQUENCY_HZ,
    MIN_ALERT_MINUTES,
    SETTINGS_DIR_NAME,
    SETTINGS_FILE_NAME,
)

log = logging.getLogger(__name__)


def _settings_path() -> Path:
    appdata = os.environ.get("APPDATA") or Path.home()
    return Path(appdata) / SETTINGS_DIR_NAME / SETTINGS_FILE_NAME


@dataclass
class Settings:
    alert_minutes: Dict[str, int] = field(default_factory=lambda: dict(DEFAULT_ALERT_MINUTES))
    enabled: Dict[str, bool] = field(default_factory=lambda: dict(DEFAULT_ENABLED))
    mute_all: bool = False
    window_bg: str = DEFAULT_WINDOW_BG
    window_x: int | None = None
    window_y: int | None = None
    alert_bg: str = DEFAULT_ALERT_BG
    alert_x: int | None = None
    alert_y: int | None = None
    settings_x: int | None = None
    settings_y: int | None = None
    alert_auto_dismiss: bool = False
    alert_frequency_hz: int = DEFAULT_ALERT_FREQUENCY_HZ
    suppress_when_not_gaming: bool = False
    run_on_startup: bool = False

    def get_alert_minutes(self, event_type: str) -> int:
        return self.alert_minutes.get(event_type, DEFAULT_ALERT_MINUTES.get(event_type, 5))

    def is_enabled(self, event_type: str) -> bool:
        return self.enabled.get(event_type, True)


def load_settings(path: Path | None = None) -> Settings:
    """Load settings from disk. Returns defaults silently on any failure."""
    target = path or _settings_path()
    try:
        with open(target) as f:
            data = json.load(f)
        if not isinstance(data, dict):
            return Settings()
    except Exception:
        return Settings()

    alert_minutes = dict(DEFAULT_ALERT_MINUTES)
    raw_alert = data.get("alert_minutes") or {}
    for et in ALL_EVENT_TYPES:
        val = raw_alert.get(et)
        if isinstance(val, int) and MIN_ALERT_MINUTES <= val <= MAX_ALERT_MINUTES:
            alert_minutes[et] = val

    enabled = dict(DEFAULT_ENABLED)
    raw_enabled = data.get("enabled") or {}
    for et in ALL_EVENT_TYPES:
        val = raw_enabled.get(et)
        if isinstance(val, bool):
            enabled[et] = val

    mute_all = bool(data.get("mute_all", False))

    raw_bg = data.get("window_bg", DEFAULT_WINDOW_BG)
    window_bg = (
        str(raw_bg) if isinstance(raw_bg, str) and raw_bg.startswith("#") else DEFAULT_WINDOW_BG
    )

    raw_x = data.get("window_x")
    window_x = int(raw_x) if isinstance(raw_x, (int, float)) else None

    raw_y = data.get("window_y")
    window_y = int(raw_y) if isinstance(raw_y, (int, float)) else None

    raw_alert_bg = data.get("alert_bg", DEFAULT_ALERT_BG)
    alert_bg = (
        str(raw_alert_bg)
        if isinstance(raw_alert_bg, str) and raw_alert_bg.startswith("#")
        else DEFAULT_ALERT_BG
    )

    raw_ax = data.get("alert_x")
    alert_x = int(raw_ax) if isinstance(raw_ax, (int, float)) else None

    raw_ay = data.get("alert_y")
    alert_y = int(raw_ay) if isinstance(raw_ay, (int, float)) else None

    raw_sx = data.get("settings_x")
    settings_x = int(raw_sx) if isinstance(raw_sx, (int, float)) else None

    raw_sy = data.get("settings_y")
    settings_y = int(raw_sy) if isinstance(raw_sy, (int, float)) else None

    alert_auto_dismiss = bool(data.get("alert_auto_dismiss", False))
    suppress_when_not_gaming = bool(data.get("suppress_when_not_gaming", False))
    run_on_startup = bool(data.get("run_on_startup", False))

    raw_freq = data.get("alert_frequency_hz", DEFAULT_ALERT_FREQUENCY_HZ)
    alert_frequency_hz = (
        int(raw_freq)
        if isinstance(raw_freq, (int, float))
        and MIN_ALERT_FREQUENCY_HZ <= raw_freq <= MAX_ALERT_FREQUENCY_HZ
        else DEFAULT_ALERT_FREQUENCY_HZ
    )

    return Settings(
        alert_minutes=alert_minutes,
        enabled=enabled,
        mute_all=mute_all,
        window_bg=window_bg,
        window_x=window_x,
        window_y=window_y,
        alert_bg=alert_bg,
        alert_x=alert_x,
        alert_y=alert_y,
        settings_x=settings_x,
        settings_y=settings_y,
        alert_auto_dismiss=alert_auto_dismiss,
        alert_frequency_hz=alert_frequency_hz,
        suppress_when_not_gaming=suppress_when_not_gaming,
        run_on_startup=run_on_startup,
    )


def save_settings(settings: Settings, path: Path | None = None) -> None:
    """Atomically save settings to disk."""
    target = path or _settings_path()
    target.parent.mkdir(parents=True, exist_ok=True)

    data = {
        "alert_minutes": settings.alert_minutes,
        "enabled": settings.enabled,
        "mute_all": settings.mute_all,
        "window_bg": settings.window_bg,
        "window_x": settings.window_x,
        "window_y": settings.window_y,
        "alert_bg": settings.alert_bg,
        "alert_x": settings.alert_x,
        "alert_y": settings.alert_y,
        "settings_x": settings.settings_x,
        "settings_y": settings.settings_y,
        "alert_auto_dismiss": settings.alert_auto_dismiss,
        "alert_frequency_hz": settings.alert_frequency_hz,
        "suppress_when_not_gaming": settings.suppress_when_not_gaming,
        "run_on_startup": settings.run_on_startup,
    }

    tmp = target.with_suffix(".tmp")
    try:
        tmp.write_text(json.dumps(data, indent=2))
        tmp.replace(target)
    except Exception:
        log.exception("Failed to save settings to %s", target)
        try:
            tmp.unlink(missing_ok=True)
        except Exception:
            pass
