# Generated By: Claude Code (claude-sonnet-4-6)
"""Windows startup registry helpers — run D4 Timer at login."""

from __future__ import annotations

import logging
import sys

import winreg

log = logging.getLogger(__name__)

_REG_RUN_PATH = r"Software\Microsoft\Windows\CurrentVersion\Run"
_REG_VALUE_NAME = "D4Timer"


def _startup_cmd() -> str:
    pythonw = sys.executable.replace("python.exe", "pythonw.exe")
    return f'"{pythonw}" -m d4_timer'


def set_run_on_startup(enabled: bool) -> None:
    """Write or remove the startup registry entry under HKCU."""
    try:
        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, _REG_RUN_PATH, 0, winreg.KEY_SET_VALUE)
        try:
            if enabled:
                winreg.SetValueEx(key, _REG_VALUE_NAME, 0, winreg.REG_SZ, _startup_cmd())
                log.info("Startup entry set: %s", _startup_cmd())
            else:
                try:
                    winreg.DeleteValue(key, _REG_VALUE_NAME)
                    log.info("Startup entry removed")
                except FileNotFoundError:
                    pass
        finally:
            winreg.CloseKey(key)
    except Exception:
        log.warning("Failed to update startup registry entry", exc_info=True)


def get_run_on_startup() -> bool:
    """Return True if the startup registry entry currently exists."""
    try:
        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, _REG_RUN_PATH, 0, winreg.KEY_READ)
        try:
            winreg.QueryValueEx(key, _REG_VALUE_NAME)
            return True
        except FileNotFoundError:
            return False
        finally:
            winreg.CloseKey(key)
    except Exception:
        return False
