# Generated By: Claude Code (claude-sonnet-4-6)
"""System tray icon using pystray with PIL-generated icon image."""

from __future__ import annotations

import logging
from typing import Any, Callable

from PIL import Image, ImageDraw

from .config import (
    ALL_EVENT_TYPES,
    EVENT_DISPLAY_NAMES,
    TRAY_ICON_COLOR_ACTIVE,
    TRAY_ICON_COLOR_MUTED,
    TRAY_ICON_NAME,
    TRAY_ICON_SIZE,
)

log = logging.getLogger(__name__)


def generate_icon_image(muted: bool = False) -> Image.Image:
    """Generate a PIL Image for the tray icon — filled circle."""
    size = TRAY_ICON_SIZE
    image = Image.new("RGBA", size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    color = TRAY_ICON_COLOR_MUTED if muted else TRAY_ICON_COLOR_ACTIVE
    margin = 4
    draw.ellipse(
        [margin, margin, size[0] - margin, size[1] - margin],
        fill=color,
    )
    return image


def create_tray_icon(
    on_click: Callable,
    on_quit: Callable,
    on_toggle_mute: Callable,
    on_settings: Callable,
    on_test_alert: Callable,
    on_toggle_event: Callable[[str], None],
    is_event_enabled: Callable[[str], bool],
    is_muted: Callable[[], bool],
) -> Any:
    """Create and return a pystray Icon (not yet run)."""
    import pystray

    icon_image = generate_icon_image(muted=False)

    def _make_event_item(event_type: str) -> pystray.MenuItem:
        display_name = EVENT_DISPLAY_NAMES.get(event_type, event_type)
        et = event_type
        return pystray.MenuItem(
            display_name,
            lambda icon, item: on_toggle_event(et),
            checked=lambda item: is_event_enabled(et),
        )

    menu = pystray.Menu(
        pystray.MenuItem("Open", on_click, default=True),
        pystray.MenuItem("Mute", on_toggle_mute, checked=lambda item: is_muted()),
        pystray.MenuItem("Settings", on_settings),
        pystray.MenuItem("Test Alert", on_test_alert),
        pystray.Menu.SEPARATOR,
        *[_make_event_item(et) for et in ALL_EVENT_TYPES],
        pystray.Menu.SEPARATOR,
        pystray.MenuItem("Quit", on_quit),
    )

    icon = pystray.Icon(
        name=TRAY_ICON_NAME,
        icon=icon_image,
        title=TRAY_ICON_NAME,
        menu=menu,
    )
    return icon
