# Generated By: Claude Code (claude-sonnet-4-6)
"""System tray icon using pystray with PIL-generated icon image."""

from __future__ import annotations

import logging
from typing import Callable

from PIL import Image, ImageDraw

from .config import (
    TRAY_ICON_COLOR_ACTIVE,
    TRAY_ICON_COLOR_MUTED,
    TRAY_ICON_NAME,
    TRAY_ICON_SIZE,
)

log = logging.getLogger(__name__)


def generate_icon_image(muted: bool = False) -> Image.Image:
    """Generate a PIL Image for the tray icon — filled circle."""
    size = TRAY_ICON_SIZE
    image = Image.new("RGBA", size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    color = TRAY_ICON_COLOR_MUTED if muted else TRAY_ICON_COLOR_ACTIVE
    margin = 4
    draw.ellipse(
        [margin, margin, size[0] - margin, size[1] - margin],
        fill=color,
    )
    return image


def create_tray_icon(
    on_click: Callable,
    on_quit: Callable,
    on_toggle_mute: Callable,
) -> object:
    """Create and return a pystray Icon (not yet run)."""
    import pystray

    icon_image = generate_icon_image(muted=False)

    menu = pystray.Menu(
        pystray.MenuItem("Open", on_click, default=True),
        pystray.MenuItem("Toggle Mute", on_toggle_mute),
        pystray.Menu.SEPARATOR,
        pystray.MenuItem("Quit", on_quit),
    )

    icon = pystray.Icon(
        name=TRAY_ICON_NAME,
        icon=icon_image,
        title=TRAY_ICON_NAME,
        menu=menu,
    )
    return icon
