# Generated By: Claude Code (claude-sonnet-4-6)
"""Alert popup window with configurable bg, position memory, and optional auto-dismiss."""

from __future__ import annotations

import tkinter as tk
from typing import Callable

from ..api import EventData
from ..config import (
    ALERT_AUTO_DISMISS_MS,
    ALERT_WINDOW_TITLE,
    EVENT_DISPLAY_NAMES,
)
from ..settings import Settings


class AlertWindow:
    """Toplevel alert window — topmost, dark bg, position-persistent."""

    def __init__(
        self,
        root: tk.Tk,
        event: EventData,
        settings: Settings,
        save_fn: Callable[[], None],
    ):
        self._root = root
        self._event = event
        self._settings = settings
        self._save_fn = save_fn
        self._window: tk.Toplevel | None = None

    def show(self) -> None:
        self._build()
        if self._settings.alert_auto_dismiss:
            self._schedule_dismiss()

    def _build(self) -> None:
        bg = self._settings.alert_bg
        win = tk.Toplevel(self._root)
        win.title(ALERT_WINDOW_TITLE)
        win.resizable(False, False)
        win.wm_attributes("-topmost", True)
        win.wm_attributes("-toolwindow", True)
        win.configure(bg=bg)  # type: ignore[call-arg]
        win.protocol("WM_DELETE_WINDOW", self._on_close)

        if self._settings.alert_x is not None and self._settings.alert_y is not None:
            win.geometry(f"+{self._settings.alert_x}+{self._settings.alert_y}")

        event_name = EVENT_DISPLAY_NAMES.get(self._event.event_type, self._event.event_type)

        frame = tk.Frame(win, bg=bg, padx=16, pady=16)
        frame.pack(fill=tk.BOTH, expand=True)

        tk.Label(
            frame,
            text=f"\u26a0 {event_name} starting soon!",
            font=("Segoe UI", 13, "bold"),
            bg=bg,
            fg="#ffffff",
        ).pack(pady=(0, 6))

        details = []
        if self._event.boss_name:
            details.append(f"Boss: {self._event.boss_name}")
        if self._event.zone_name:
            details.append(f"Zone: {self._event.zone_name}")

        if details:
            tk.Label(
                frame,
                text="\n".join(details),
                bg=bg,
                fg="#cccccc",
                font=("Segoe UI", 10),
            ).pack()

        tk.Button(
            frame,
            text="Dismiss",
            command=self._on_close,
            bg="#444444",
            fg="#ffffff",
            activebackground="#666666",
            relief=tk.FLAT,
            padx=12,
            pady=4,
        ).pack(pady=(12, 0))

        self._window = win

    def _on_close(self) -> None:
        if self._window and self._window.winfo_exists():
            self._settings.alert_x = self._window.winfo_x()
            self._settings.alert_y = self._window.winfo_y()
            self._save_fn()
            self._window.destroy()

    def _schedule_dismiss(self) -> None:
        if self._window:
            self._window.after(ALERT_AUTO_DISMISS_MS, self._dismiss)

    def _dismiss(self) -> None:
        if self._window and self._window.winfo_exists():
            self._on_close()
