# Generated By: Claude Code (claude-sonnet-4-6)
"""Auto-dismissing alert popup window."""

from __future__ import annotations

import tkinter as tk
from tkinter import ttk

from ..api import EventData
from ..config import (
    ALERT_AUTO_DISMISS_MS,
    ALERT_WINDOW_TITLE,
    EVENT_DISPLAY_NAMES,
)


class AlertWindow:
    """Transient Toplevel that auto-dismisses after ALERT_AUTO_DISMISS_MS."""

    def __init__(self, root: tk.Tk, event: EventData):
        self._root = root
        self._event = event
        self._window: tk.Toplevel | None = None

    def show(self) -> None:
        self._build()
        self._schedule_dismiss()

    def _build(self) -> None:
        win = tk.Toplevel(self._root)
        win.title(ALERT_WINDOW_TITLE)
        win.resizable(False, False)
        win.wm_attributes("-topmost", True)
        win.wm_attributes("-toolwindow", True)

        event_name = EVENT_DISPLAY_NAMES.get(self._event.event_type, self._event.event_type)

        frame = ttk.Frame(win, padding=16)
        frame.pack(fill=tk.BOTH, expand=True)

        ttk.Label(
            frame,
            text=f"\u26a0 {event_name} starting soon!",
            font=("Segoe UI", 13, "bold"),
        ).pack(pady=(0, 6))

        details = []
        if self._event.boss_name:
            details.append(f"Boss: {self._event.boss_name}")
        if self._event.zone_name:
            details.append(f"Zone: {self._event.zone_name}")

        if details:
            ttk.Label(frame, text="\n".join(details)).pack()

        ttk.Button(frame, text="Dismiss", command=win.destroy).pack(pady=(12, 0))

        self._window = win

    def _schedule_dismiss(self) -> None:
        if self._window:
            self._window.after(ALERT_AUTO_DISMISS_MS, self._dismiss)

    def _dismiss(self) -> None:
        if self._window and self._window.winfo_exists():
            self._window.destroy()
