# Generated By: Claude Code (claude-sonnet-4-6)
"""Main popup window showing countdown timers for all events."""

from __future__ import annotations

import tkinter as tk
from tkinter import ttk
from typing import TYPE_CHECKING

from ..config import (
    ALL_EVENT_TYPES,
    EVENT_DISPLAY_NAMES,
    MAIN_WINDOW_HEIGHT,
    MAIN_WINDOW_TITLE,
    MAIN_WINDOW_WIDTH,
)

if TYPE_CHECKING:
    from ..controller import AppController


class MainWindow:
    """tk.Toplevel showing three event countdown rows."""

    def __init__(self, root: tk.Tk, controller: "AppController"):
        self._root = root
        self._controller = controller
        self._window: tk.Toplevel | None = None
        self._countdown_vars: dict[str, tk.StringVar] = {}

    def show(self) -> None:
        if self._window and self._window.winfo_exists():
            self._window.lift()
            self._window.focus_force()
            return
        self._build()

    def hide(self) -> None:
        if self._window and self._window.winfo_exists():
            self._window.withdraw()

    def update_countdowns(self, countdowns: dict[str, str]) -> None:
        for event_type, text in countdowns.items():
            var = self._countdown_vars.get(event_type)
            if var:
                var.set(text)

    def _build(self) -> None:
        win = tk.Toplevel(self._root)
        win.title(MAIN_WINDOW_TITLE)
        win.resizable(False, False)
        win.wm_attributes("-toolwindow", True)
        win.protocol("WM_DELETE_WINDOW", self.hide)

        win.geometry(f"{MAIN_WINDOW_WIDTH}x{MAIN_WINDOW_HEIGHT}")

        frame = ttk.Frame(win, padding=12)
        frame.pack(fill=tk.BOTH, expand=True)

        # Event countdown rows
        self._countdown_vars = {}
        for row_idx, event_type in enumerate(ALL_EVENT_TYPES):
            label = EVENT_DISPLAY_NAMES.get(event_type, event_type)
            ttk.Label(frame, text=label + ":", anchor="w", width=14).grid(
                row=row_idx, column=0, sticky="w", pady=2
            )
            var = tk.StringVar(value="--:--:--")
            self._countdown_vars[event_type] = var
            ttk.Label(frame, textvariable=var, font=("Consolas", 13)).grid(
                row=row_idx, column=1, sticky="w", padx=8
            )

        # Button row
        btn_frame = ttk.Frame(frame)
        btn_frame.grid(row=len(ALL_EVENT_TYPES), column=0, columnspan=2, pady=(10, 0))

        ttk.Button(
            btn_frame,
            text="Mute All",
            command=self._controller.toggle_mute,
        ).pack(side=tk.LEFT, padx=4)

        ttk.Button(
            btn_frame,
            text="Settings",
            command=self._controller.open_settings,
        ).pack(side=tk.LEFT, padx=4)

        self._window = win

    @property
    def is_visible(self) -> bool:
        return bool(
            self._window
            and self._window.winfo_exists()
            and self._window.winfo_viewable()
        )
