# Generated By: Claude Code (claude-sonnet-4-6)
"""Modal settings editor window."""

from __future__ import annotations

import tkinter as tk
from tkinter import colorchooser, ttk
from typing import Callable

from ..config import ALL_EVENT_TYPES, EVENT_DISPLAY_NAMES
from ..settings import Settings


class SettingsWindow:
    """Modal Toplevel for editing per-event alert settings."""

    def __init__(
        self,
        root: tk.Tk,
        settings: Settings,
        on_save: Callable[[Settings], None],
        on_close_pos: Callable[[int, int], None] | None = None,
    ):
        self._root = root
        self._settings = settings
        self._on_save = on_save
        self._on_close_pos = on_close_pos
        self._window: tk.Toplevel | None = None

    def show(self) -> None:
        if self._window and self._window.winfo_exists():
            self._window.lift()
            return
        self._build()

    def _save_pos(self) -> None:
        if self._on_close_pos and self._window and self._window.winfo_exists():
            self._on_close_pos(self._window.winfo_x(), self._window.winfo_y())

    def _build(self) -> None:
        win = tk.Toplevel(self._root)
        win.title("D4 Timer — Settings")
        win.resizable(False, False)
        win.grab_set()  # Modal

        if self._settings.settings_x is not None and self._settings.settings_y is not None:
            win.geometry(f"+{self._settings.settings_x}+{self._settings.settings_y}")

        def _on_wm_close() -> None:
            self._save_pos()
            win.destroy()

        win.protocol("WM_DELETE_WINDOW", _on_wm_close)

        frame = ttk.Frame(win, padding=16)
        frame.pack(fill=tk.BOTH, expand=True)

        # Header row
        ttk.Label(frame, text="Event", font=("Segoe UI", 10, "bold")).grid(
            row=0, column=0, sticky="w", padx=4
        )
        ttk.Label(frame, text="Alert (min)", font=("Segoe UI", 10, "bold")).grid(
            row=0, column=1, sticky="w", padx=4
        )
        ttk.Label(frame, text="Enabled", font=("Segoe UI", 10, "bold")).grid(
            row=0, column=2, sticky="w", padx=4
        )

        alert_vars: dict[str, tk.StringVar] = {}
        enabled_vars: dict[str, tk.BooleanVar] = {}

        for row_idx, event_type in enumerate(ALL_EVENT_TYPES, start=1):
            label = EVENT_DISPLAY_NAMES.get(event_type, event_type)

            ttk.Label(frame, text=label).grid(row=row_idx, column=0, sticky="w", padx=4, pady=3)

            alert_var = tk.StringVar(value=str(self._settings.get_alert_minutes(event_type)))
            alert_vars[event_type] = alert_var
            ttk.Spinbox(
                frame,
                from_=1,
                to=60,
                width=6,
                textvariable=alert_var,
            ).grid(row=row_idx, column=1, padx=4)

            enabled_var = tk.BooleanVar(value=self._settings.is_enabled(event_type))
            enabled_vars[event_type] = enabled_var
            ttk.Checkbutton(frame, variable=enabled_var).grid(row=row_idx, column=2, padx=4)

        # Appearance section
        sep_row = len(ALL_EVENT_TYPES) + 1
        ttk.Separator(frame, orient="horizontal").grid(
            row=sep_row, column=0, columnspan=3, sticky="ew", pady=(10, 6)
        )

        window_bg_val = [self._settings.window_bg]
        alert_bg_val = [self._settings.alert_bg]

        def _add_color_row(row: int, label: str, current: list[str]) -> None:
            ttk.Label(frame, text=label).grid(row=row, column=0, sticky="w", padx=4, pady=3)
            preview = tk.Label(frame, width=4, bg=current[0])
            preview.grid(row=row, column=1, padx=4, sticky="w")

            def _pick() -> None:
                result = colorchooser.askcolor(color=current[0], title=f"Choose {label}")
                if result[1]:
                    current[0] = result[1]
                    preview.configure(bg=result[1])  # type: ignore[call-arg]

            ttk.Button(frame, text="Pick…", command=_pick, width=7).grid(row=row, column=2, padx=4)

        _add_color_row(sep_row + 1, "Window bg", window_bg_val)
        _add_color_row(sep_row + 2, "Alert bg", alert_bg_val)

        auto_dismiss_var = tk.BooleanVar(value=self._settings.alert_auto_dismiss)
        ttk.Label(frame, text="Auto-dismiss alerts").grid(
            row=sep_row + 3, column=0, sticky="w", padx=4, pady=3
        )
        ttk.Checkbutton(frame, variable=auto_dismiss_var).grid(row=sep_row + 3, column=2, padx=4)

        btn_frame = ttk.Frame(frame)
        btn_frame.grid(row=sep_row + 4, column=0, columnspan=3, pady=(12, 0))

        def _save() -> None:
            new_alert = {}
            for et, var in alert_vars.items():
                try:
                    val = int(var.get())
                    new_alert[et] = max(1, min(60, val))
                except ValueError:
                    new_alert[et] = self._settings.get_alert_minutes(et)

            new_enabled = {et: var.get() for et, var in enabled_vars.items()}

            new_settings = Settings(
                alert_minutes=new_alert,
                enabled=new_enabled,
                mute_all=self._settings.mute_all,
                window_bg=window_bg_val[0],
                window_x=self._settings.window_x,
                window_y=self._settings.window_y,
                alert_bg=alert_bg_val[0],
                alert_x=self._settings.alert_x,
                alert_y=self._settings.alert_y,
                settings_x=self._settings.settings_x,
                settings_y=self._settings.settings_y,
                alert_auto_dismiss=auto_dismiss_var.get(),
            )
            self._save_pos()
            self._on_save(new_settings)
            win.destroy()

        ttk.Button(btn_frame, text="Save", command=_save).pack(side=tk.LEFT, padx=6)
        ttk.Button(btn_frame, text="Cancel", command=_on_wm_close).pack(side=tk.LEFT, padx=6)

        self._window = win
